/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.aluguel.ferramenta.View;

/**
 *
 * @author Pichau
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoAmigos = new javax.swing.JButton();
        botaoFerramentas = new javax.swing.JButton();
        botaoEmprestimos = new javax.swing.JButton();
        labelAlugelDeFerramentas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botaoAmigos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoAmigos.setText("amigos");
        botaoAmigos.setMaximumSize(new java.awt.Dimension(97, 27));
        botaoAmigos.setMinimumSize(new java.awt.Dimension(97, 27));
        botaoAmigos.setPreferredSize(new java.awt.Dimension(97, 27));
        botaoAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAmigosActionPerformed(evt);
            }
        });

        botaoFerramentas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoFerramentas.setText("ferramentas");
        botaoFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFerramentasActionPerformed(evt);
            }
        });

        botaoEmprestimos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoEmprestimos.setText("empréstimos ");
        botaoEmprestimos.setMaximumSize(new java.awt.Dimension(97, 27));
        botaoEmprestimos.setMinimumSize(new java.awt.Dimension(97, 27));
        botaoEmprestimos.setPreferredSize(new java.awt.Dimension(97, 27));
        botaoEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEmprestimosActionPerformed(evt);
            }
        });

        labelAlugelDeFerramentas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelAlugelDeFerramentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAlugelDeFerramentas.setText("alugel de ferramentas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(labelAlugelDeFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(botaoAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelAlugelDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEmprestimosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEmprestimosActionPerformed

    private void botaoAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAmigosActionPerformed
        TelaAmigos tela = new TelaAmigos();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoAmigosActionPerformed

    private void botaoFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFerramentasActionPerformed
        TelaFerramentas tela = new TelaFerramentas();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoFerramentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAmigos;
    private javax.swing.JButton botaoEmprestimos;
    private javax.swing.JButton botaoFerramentas;
    private javax.swing.JLabel labelAlugelDeFerramentas;
    // End of variables declaration//GEN-END:variables
}
