/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.aluguel.ferramenta.View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projeto.aluguel.ferramenta.DAO.FerramentaDAO;
import projeto.aluguel.ferramenta.Model.Ferramenta;

/**
 *
 * @author Pichau
 */
public class TelaFerramentas extends javax.swing.JFrame {

    /**
     * Creates new form TelaFerramentas
     */
    public TelaFerramentas() {
        initComponents();
        
        readJTable();
    }
    
    public void readJTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaDeFerramentas.getModel();
        modelo.setNumRows(0);
        FerramentaDAO dao = new FerramentaDAO();
        
        for (Ferramenta a: dao.Read()) {
            
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getMarca(),
                a.getPreco()
            });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrarFerramenta = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoAtualizarFerramenta = new javax.swing.JButton();
        botaoEmprestarFerramenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoRemovaerFerramenta1 = new javax.swing.JButton();
        campoTextoFerramenta = new javax.swing.JTextField();
        campoTextoMarca = new javax.swing.JTextField();
        campoTextoPreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDeFerramentas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(585, 395));
        setResizable(false);

        botaoCadastrarFerramenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCadastrarFerramenta.setText("cadastrar ferramenta");
        botaoCadastrarFerramenta.setMaximumSize(new java.awt.Dimension(120, 30));
        botaoCadastrarFerramenta.setMinimumSize(new java.awt.Dimension(120, 30));
        botaoCadastrarFerramenta.setPreferredSize(new java.awt.Dimension(120, 30));
        botaoCadastrarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarFerramentaActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoVoltar.setText("voltar");
        botaoVoltar.setMaximumSize(new java.awt.Dimension(120, 30));
        botaoVoltar.setMinimumSize(new java.awt.Dimension(120, 30));
        botaoVoltar.setPreferredSize(new java.awt.Dimension(120, 30));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoAtualizarFerramenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoAtualizarFerramenta.setText("atualizar ferramenta");
        botaoAtualizarFerramenta.setMaximumSize(new java.awt.Dimension(120, 30));
        botaoAtualizarFerramenta.setMinimumSize(new java.awt.Dimension(120, 30));
        botaoAtualizarFerramenta.setPreferredSize(new java.awt.Dimension(120, 30));
        botaoAtualizarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarFerramentaActionPerformed(evt);
            }
        });

        botaoEmprestarFerramenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoEmprestarFerramenta.setText("emprestar ferramenta");
        botaoEmprestarFerramenta.setMaximumSize(new java.awt.Dimension(120, 30));
        botaoEmprestarFerramenta.setMinimumSize(new java.awt.Dimension(120, 30));
        botaoEmprestarFerramenta.setPreferredSize(new java.awt.Dimension(120, 30));
        botaoEmprestarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEmprestarFerramentaActionPerformed(evt);
            }
        });

        botaoRemovaerFerramenta1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoRemovaerFerramenta1.setText("remover ferramenta");
        botaoRemovaerFerramenta1.setMaximumSize(new java.awt.Dimension(120, 30));
        botaoRemovaerFerramenta1.setMinimumSize(new java.awt.Dimension(120, 30));
        botaoRemovaerFerramenta1.setPreferredSize(new java.awt.Dimension(120, 30));
        botaoRemovaerFerramenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemovaerFerramenta1ActionPerformed(evt);
            }
        });

        campoTextoFerramenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campoTextoFerramenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoTextoMarca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campoTextoMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoTextoPreco.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campoTextoPreco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoPrecoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Ferramenta");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Marca");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Preço");

        tabelaDeFerramentas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaDeFerramentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ferramenta", "Marca", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDeFerramentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDeFerramentasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaDeFerramentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(botaoEmprestarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoCadastrarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoRemovaerFerramenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoAtualizarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTextoFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTextoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(campoTextoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEmprestarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtualizarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemovaerFerramenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEmprestarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEmprestarFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEmprestarFerramentaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void campoTextoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoPrecoActionPerformed

    private void botaoCadastrarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarFerramentaActionPerformed
         
//        DefaultTableModel dtmProdutos = (DefaultTableModel) tabelaDeFerramentas.getModel();
//        Object[] dados = {campoTextoFerramenta.getText(), campoTextoMarca.getText(), campoTextoPreco.getText()};
//        if(!campoTextoFerramenta.getText().trim().isEmpty()){
//            dtmProdutos.addRow(dados);
//        }else{
//            
//            JOptionPane.showMessageDialog(null, "Informe todos os dados!", "Erro", JOptionPane.ERROR_MESSAGE);
//        }
        Ferramenta ferramenta = new Ferramenta();
        FerramentaDAO dao = new FerramentaDAO();
        
        ferramenta.setNome(campoTextoFerramenta.getText());
        ferramenta.setMarca(campoTextoMarca.getText());
        try{
            ferramenta.setPreco(Double.parseDouble(campoTextoPreco.getText()));
            dao.Create(ferramenta);


        campoTextoFerramenta.setText(null);
        campoTextoMarca.setText(null);
        campoTextoPreco.setText(null);
        }catch(NumberFormatException ex){
            
            JOptionPane.showMessageDialog(null, "Informe o preço corretamente!");
            campoTextoPreco .setText("0");
        }
        
        readJTable();
 
    }//GEN-LAST:event_botaoCadastrarFerramentaActionPerformed

    private void botaoRemovaerFerramenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemovaerFerramenta1ActionPerformed
        
        if(tabelaDeFerramentas.getSelectedRow() != -1){
            
            Ferramenta ferramenta = new Ferramenta();
            FerramentaDAO dao = new FerramentaDAO();
            
            ferramenta.setId((int)tabelaDeFerramentas.getValueAt(tabelaDeFerramentas.getSelectedRow(), 0));
            dao.Delete(ferramenta);
            
            campoTextoFerramenta.setText(null);
            campoTextoMarca.setText(null);
            campoTextoPreco.setText(null);
            
            readJTable();
        }else{
            
            JOptionPane.showMessageDialog(null, "Selecione algo para excluir!");
        }
        
    }//GEN-LAST:event_botaoRemovaerFerramenta1ActionPerformed

    private void tabelaDeFerramentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeFerramentasMouseClicked
        if(tabelaDeFerramentas.getSelectedRow() != -1){
            
            campoTextoFerramenta.setText(tabelaDeFerramentas.getValueAt(tabelaDeFerramentas.getSelectedRow(), 1).toString());
            campoTextoMarca.setText(tabelaDeFerramentas.getValueAt(tabelaDeFerramentas.getSelectedRow(), 2).toString());
            campoTextoPreco.setText(tabelaDeFerramentas.getValueAt(tabelaDeFerramentas.getSelectedRow(), 3).toString());
            
        }
    }//GEN-LAST:event_tabelaDeFerramentasMouseClicked

    private void botaoAtualizarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarFerramentaActionPerformed
        
        if(tabelaDeFerramentas.getSelectedRow() != -1){
            
            if(!campoTextoFerramenta.getText().trim().isEmpty()){
            
            Ferramenta ferramenta = new Ferramenta();
          FerramentaDAO dao = new FerramentaDAO();
          
          ferramenta.setNome(campoTextoFerramenta.getText());
          ferramenta.setMarca(campoTextoMarca.getText());
          try{
              ferramenta.setPreco(Double.parseDouble(campoTextoPreco.getText()));
              ferramenta.setId((int)tabelaDeFerramentas.getValueAt(tabelaDeFerramentas.getSelectedRow(), 0));
              dao.Update(ferramenta);
              
              campoTextoFerramenta.setText(null);
            campoTextoMarca.setText(null);
            campoTextoPreco.setText(null);
              
              tabelaDeFerramentas.clearSelection();
          }catch(NumberFormatException ex){
              JOptionPane.showMessageDialog(null, "Informe o preço corretamente!");
          }
          readJTable();
            
   
            }else{
                
                JOptionPane.showMessageDialog(null, "Coloque o nome da ferramenta!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Selecione algo que queira atualizar!");
        }
       
           
            
        
    }//GEN-LAST:event_botaoAtualizarFerramentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFerramentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizarFerramenta;
    private javax.swing.JButton botaoCadastrarFerramenta;
    private javax.swing.JButton botaoEmprestarFerramenta;
    private javax.swing.JButton botaoRemovaerFerramenta1;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoTextoFerramenta;
    private javax.swing.JTextField campoTextoMarca;
    private javax.swing.JTextField campoTextoPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaDeFerramentas;
    // End of variables declaration//GEN-END:variables
}
